# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy using github action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 16
        
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref == 'ref/heads/master'
      with:
        folder: build # The folder the action should deploy.
